# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.0.2-4-g02eefe5
_src_path: /home/trisdoan/projects/trobz-python-template
author_email: doaminhtri8183@gmail.com
author_username: trisdoan
enable_github_action: true
package_name: trobz_local
project_description: ''
project_name: trobz_local
publish_to_pypi: false
repository_name: local.py
repository_namespace: trobz
