[tools]
uv = [
  "copier",
  "oca-port",
  "odooly",
  "odoo-venv",
  "odoo-addons-path"
]
system_packages = ["postgresql"]
skills = ["https://github.com/trobz/public-skills", "git@github.com:trobz/skills.git"]
